package com.example.coctailapp.Models

data class drink (
    var idDrink : String? = "",
    var strDrink : String? = "",
    var strDrinkAlternate : String? = "",
    var strDrinkES: String? = "",
    var strDrinkDE: String? = "",
    var strDrinkFR: String? = "",
    var strTags : String? = "",
    var strCategory : String? = "",
    var strAlcoholic : String? = "",
    var strInstructions : String? = "",
    var strGlass : String? = "",
    var strDrinkThumb : String? = "",
    var strIngredient1 : String? = "",
    var strMeasure1 : String? = "",
    var strCreativeCommonsConfirmed : String? = ""

)


/*"strIngredient1":"Gin",
"strIngredient2":"Grand Marnier",
"strIngredient3":"Lemon Juice",
"strIngredient4":"Grenadine",
"strIngredient5":null,
"strIngredient6":null,
"strIngredient7":null,
"strIngredient8":null,
"strIngredient9":null,
"strIngredient10":null,
"strIngredient11":null,
"strIngredient12":null,
"strIngredient13":null,
"strIngredient14":null,
"strIngredient15":null,
"strCategory":"Cocktail",
"strIBA":null,
"strAlcoholic":"Alcoholic",

"strInstructionsES":null,

"strInstructionsFR":null,
"strInstructionsZH-HANS":null,
"strInstructionsZH-HANT":null,

"strIngredient1":"Gin",
"strIngredient2":"Grand Marnier",
"strIngredient3":"Lemon Juice",
"strIngredient4":"Grenadine",
"strIngredient5":null,
"strIngredient6":null,
"strIngredient7":null,
"strIngredient8":null,
"strIngredient9":null,
"strIngredient10":null,
"strIngredient11":null,
"strIngredient12":null,
"strIngredient13":null,
"strIngredient14":null,
"strIngredient15":null,
"strMeasure1":"1 3\/4 shot ",
"strMeasure2":"1 Shot ",
"strMeasure3":"1\/4 Shot",
"strMeasure4":"1\/8 Shot",
"strMeasure5":null,
"strMeasure6":null,
"strMeasure7":null,
"strMeasure8":null,
"strMeasure9":null,
"strMeasure10":null,
"strMeasure11":null,
"strMeasure12":null,
"strMeasure13":null,
"strMeasure14":null,
"strMeasure15":null,
"strCreativeCommonsConfirmed":"No",
"dateModified":"2017-09-07 21:42:09"8*/;